name: call_ui_kit_example
description: Example app demonstrating call_ui_kit package.
publish_to: 'none'

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  call_ui_kit:
    path: ../

flutter:
  uses-material-design: true
